### ISSUE TITLE
help to add dooya.curtain.m2 

### ISSUE THREAD

**Issue by merv2k4** [merdok/homebridge-miot#7] opened 2021-03-29 16:51 UTC
Hi marcin,

thanks again for the help in adding my devices to the plugin.

This is the data of the curtain

hoobs@hoobs:~ $ miio protocol call  192.168.100.81 get_properties '[{"did":"244127254","siid": 2,"piid":4}]'
 INFO  Attempting to call get_properties on 192.168.100.81

 INFO  Device found, making call

 INFO  Got result:
[
  {
    "did": "244127254",
    "siid": 2,
    "piid": 4,
    "code": 0,
    "value": 1
  }
]

oobs@hoobs:~ $ miio protocol call  192.168.100.81 get_properties '[{"did":"244127254","siid": 1,"piid":1}]'
 INFO  Attempting to call get_properties on 192.168.100.81

 INFO  Device found, making call

 INFO  Got result:
[
  {
    "did": "244127254",
    "siid": 1,
    "piid": 1,
    "code": -4004
  }
]

hoobs@hoobs:~ $ miio protocol call  192.168.100.81 get_properties '[{"did":"244127254","siid": 2,"piid":8}]'
 INFO  Attempting to call get_properties on 192.168.100.81

 INFO  Device found, making call

 INFO  Got result:
[
  {
    "did": "244127254",
    "siid": 2,
    "piid": 8,
    "code": 0,
    "value": false
  }
]

hoobs@hoobs:~ $ miio protocol call  192.168.100.81 get_properties '[{"did":"244127254","siid": 2,"piid":6}]'
 INFO  Attempting to call get_properties on 192.168.100.81

 INFO  Device found, making call

 INFO  Got result:
[
  {
    "did": "244127254",
    "siid": 2,
    "piid": 6,
    "code": 0,
    "value": 0
  }
]

hoobs@hoobs:~ $ miio inspect 192.168.100.81
 INFO  Attempting to inspect 192.168.100.81

Device ID: 244127254
Model info: dooya.curtain.m2
Address: 192.168.100.81
Token: dc28025c65b38b95d5c0492a79fc86b9 via stored token
Support: At least generic

Type info: miio
Capabilities:

Firmware version: 2.1.3
Hardware version: esp8266
MCU firmware version: 0009

WiFi: merv_S1 (E0:63:DA:EA:A1:09) RSSI: -64
WiFi firmware version: 8903c22

Remote access (Mi Home App): Maybe

**Comment by merdok** [comment] 2021-03-29 17:01
This will take some time since i need to add a new device type: curtains.
But we already confirmed that it is a miot device so there should be no issue with adding this device.
Will let you know when support is added.

**Comment by merdok** [comment] 2021-04-08 19:27
Support added in version 0.6.0. Please let me know if it works.

**Comment by merv2k4** [comment] 2021-04-09 03:20
Thanks Marcin :) will try it out tomorrow

**Comment by merdok** [comment] 2021-04-09 06:11
Ok!

Oh, that is strange that it is not available. Maybe just a short delay... Alternatively you can use npm directly to update the plugin package, you can check how in the README.

**Comment by merv2k4** [comment] 2021-04-11 13:08
Hi Marcin,

update when thru awhiler ago.. The slider percentage works perfectly! :) 

The other switches shown with device (open, close, stop) does not work. But the slider is the only switch needed.. is it possible to hide those? Theres also a motor reverse switch, it got detected successfully.

besides that some minor warning/error message when starting the service. Does not affect the percentage slider.

4/11/2021, 8:40:45 PM (node:1817) UnhandledPromiseRejectionWarning: TypeError: this.getPositionState is not a function
4/11/2021, 8:40:45 PM at DooyaCurtainM2.isStatusClosing (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/curtain/CurtainDevice.js:70:17)
4/11/2021, 8:40:45 PM at CurtainAccessory.getPositionState (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/curtain/CurtainAccessory.js:100:28)
4/11/2021, 8:40:45 PM at CurtainAccessory.updateDeviceStatus (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/curtain/CurtainAccessory.js:162:129)
4/11/2021, 8:40:45 PM at MiotController.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:117:33)
4/11/2021, 8:40:45 PM at MiotController.emit (events.js:210:5)
4/11/2021, 8:40:45 PM at /home/hoobs/.hoobs/node_modules/homebridge-miot/lib/MiotController.js:110:18
4/11/2021, 8:40:45 PM (node:1817) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
4/11/2021, 8:40:45 PM (node:1817) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
4/11/2021, 8:40:45 PM (node:1817) UnhandledPromiseRejectionWarning: TypeError: this.getPositionState is not a function
4/11/2021, 8:40:45 PM at DooyaCurtainM2.isStatusClosing (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/curtain/CurtainDevice.js:70:17)
4/11/2021, 8:40:45 PM at CurtainAccessory.getPositionState (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/curtain/CurtainAccessory.js:100:28)
4/11/2021, 8:40:45 PM at CurtainAccessory.updateDeviceStatus (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/curtain/CurtainAccessory.js:162:129)
4/11/2021, 8:40:45 PM at MiotController.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:117:33)
4/11/2021, 8:40:45 PM at MiotController.emit (events.js:210:5)
4/11/2021, 8:40:45 PM at /home/hoobs/.hoobs/node_modules/homebridge-miot/lib/MiotController.js:110:18
4/11/2021, 8:40:45 PM (node:1817) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
4/11/2021, 8:40:45 PM (node:1817) UnhandledPromiseRejectionWarning: TypeError: this.getPositionState is not a function
4/11/2021, 8:40:45 PM at DooyaCurtainM2.isStatusClosing (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/curtain/CurtainDevice.js:70:17)
4/11/2021, 8:40:45 PM at CurtainAccessory.getPositionState (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/curtain/CurtainAccessory.js:100:28)
4/11/2021, 8:40:45 PM at CurtainAccessory.updateDeviceStatus (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/curtain/CurtainAccessory.js:162:129)
4/11/2021, 8:40:45 PM at MiotController.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:117:33)
4/11/2021, 8:40:45 PM at MiotController.emit (events.js:210:5)
4/11/2021, 8:40:45 PM at /home/hoobs/.hoobs/node_modules/homebridge-miot/lib/MiotController.js:110:18
4/11/2021, 8:40:45 PM (node:1817) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
4/11/2021, 8:40:45 PM (node:1817) UnhandledPromiseRejectionWarning: TypeError: this.getPositionState is not a function
4/11/2021, 8:40:45 PM at DooyaCurtainM2.isStatusClosing (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/curtain/CurtainDevice.js:70:17)
4/11/2021, 8:40:45 PM at CurtainAccessory.getPositionState (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/curtain/CurtainAccessory.js:100:28)
4/11/2021, 8:40:45 PM at CurtainAccessory.updateDeviceStatus (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/curtain/CurtainAccessory.js:162:129)
4/11/2021, 8:40:45 PM at MiotController.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:117:33)
4/11/2021, 8:40:45 PM at MiotController.emit (events.js:210:5)
4/11/2021, 8:40:45 PM at /home/hoobs/.hoobs/node_modules/homebridge-miot/lib/MiotController.js:110:18
4/11/2021, 8:40:45 PM (node:1817) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)

**Comment by merdok** [comment] 2021-04-11 20:45
Should now be fixed in version 0.6.2

**Comment by merv2k4** [comment] 2021-04-12 14:53
Thanks Marcin,

I have attached the debug log and run thru the curtain and fans. Everything seems to work perfectly :)

Thanks again

[hoobsdebug 12042021.log](https://github.com/merdok/homebridge-miot/files/6297653/hoobsdebug.12042021.log)

**Comment by merdok** [comment] 2021-04-12 15:25
Thanks for letting me know! Can be closed now!

**Closed by merdok** 2021-04-12 15:25 UTC
Labels: new device
