### ISSUE TITLE
Smartmi Air Purifier

### ISSUE THREAD

**Issue by limeos** [merdok/homebridge-miot#13] opened 2021-04-16 07:44 UTC
Hello, 

the Smartmi Air Purifier (zhimi.airpurifier.za1) is listed as a supported device, but I can't get it to work properly.
To determine its token, I reset the purifier's WiFi and read the token with `miio discover`. 
Then I connected the purifier to my network via the Mi-Home app on my phone. 
Then I installed `homebridge-miio` on my raspberry pi (which already had homebridge installed and working well with other devices ) and configured it accordingly. The configuration looks like this: 
```
{
    "bridge": {
        "name": "homebridge 0322",
        }, "username": "xx:xx:xx:xx:xx",
        "port": xxxxx,
        }, "pin": "xxx-xx-xxx"
    },
    }, "platforms": [
        {
            }, "devices": [
                {
                    }, "name": "smartmi air purifier",
                    }, "ip": "192.168.10.62",
                    }, "token": "xxxxxxxxxxxxxxxxxxxxxxxx",
                    }, "model": "zhimi.airpurifier.za1",
                    }, "pollingInterval": 5,
                    "buzzerControl": true,
                    "childLockControl": true,
                    "ledControl": true,
                    "horizontalSwingControl": false,
                    "verticalSwingControl": false,
                    "horizontalMoveControl": false,
                    "verticalMoveControl": false,
                    "fanLevelControl": true,
                    "ioniserControl": false,
                    "shutdownTimer": false,
                    "heatLevelControl": false,
                    "screenControl": true,
                    "dryModeControl": true,
                    "modeControl": false,
                    "lightModeControl": false,
                    "lightShutdownTimer": false,
                    "motorControl": true,
                    "motorReverseControl": false,
                    "heaterControl": true
                }
            ],
            }, "platform": "miot"
        }
    ]
}
```

Is there anything wrong with the procedure or are there any settings I should change?
Thanks in advance

**Comment by merdok** [comment] 2021-04-16 08:01
You need to post a homebridge debug log, without that it is impossible to say what the issue is. Could you do that? The complete startup log will be interesting.

**Comment by limeos** [comment] 2021-04-16 08:26
Thanks for the quick feedback. 
Yes of course I can do that, but I'm not sure what exactly to show. 
Is it just the `homebridge.log` file, that I can see with the homebridge-user in `/var/lib/homebridge`?

```
homebridge@raspberrypi:/var/lib/homebridge$ ls
accessories ccu.json homematic_config.json package-lock.json raspberrypi_HmIP-RF.000393C99B624A:1_persist.json
auth.json config.json node_modules persist raspberrypi_HmIP-RF.000393C99B6286:1_persist.json
backups homebridge.log package.json raspberrypi_HmIP-RF.000393C99B6204:1_persist.json raspberrypi_HmIP-RF.000393C99B639E:1_persist.json
```

Or is there a special debug mode that I need to start first? If so, you would have to briefly explain to me what exactly I should do.

**Comment by merdok** [comment] 2021-04-16 08:43
You have to start homebridge in debug mode after that you should a lot of output in the terminal window which should be helpful. Please check the bottom of the README on how to do that.

**Comment by limeos** [comment] 2021-04-16 08:58
Ok, so the problem seams to be the token:
```
[16.4.2021, 10:53:45] [miot] [Smartmi Luftreiniger] Error: Could not connect to device, token might be wrong
[16.4.2021, 10:53:45] [miot] [Smartmi Luftreiniger] Could not connect to the device! Retrying in 30 seconds!
```
As said I retrieved the token by resetting the WiFi of the purifier and then using `miio discover`, which gave me a 32digit value.
Would it be possible that the token is regenerated after the device is connected to my home network?
If so, how could I get the current token? 
In my home network `miio discover` results in `Token: ???`

**Comment by merdok** [comment] 2021-04-16 09:07
Yes, your token is most probably wrong. The token of the device resets every time you reset the device. For possible ways to retrieve the token have a look at the guide included in the README.

**Comment by limeos** [comment] 2021-04-16 13:59
I finally retrieved the token by the following steps:

1. iTunes-backup (unencrypted)
2. export `xxxxxxxxxxxx_mihome.sqlite` using iBackupviewer 
3. extract token using the command `miio-extract-tokens xxxxxxxxxxxx_mihome.sqlite` 

The method of resetting the purifier's Wi-Fi, connecting to that Wi-Fi and then using `miio discover` to read the token definitely does not work, as the token changes after connecting to the home network.

**Comment by merdok** [comment] 2021-04-16 14:32
As an iOS user I also always use the backup to retrieve the token and it has always worked🙂

Good that it works now👍

**Closed by merdok** 2021-04-16 14:32 UTC
