### ISSUE TITLE
the device is initialized

### ISSUE THREAD

**Issue by ddong3000** [merdok/homebridge-miot#193] opened 2022-02-02 07:12 UTC
When Homebridge restarts, the device is initialized. What should I do?

**Comment by merdok** [comment] 2022-02-02 07:47
Sorry I do not understand what you mean and what your issue is. Could you explain more detailed or provide a debug log?

**Comment by ddong3000** [comment] 2022-02-02 07:59
![E8C935DC-4526-4E89-A5E0-3C03ACEF2D2A](https://user-images.githubusercontent.com/54649785/152114978-de4a7840-dc53-4b20-b001-32be7ae89b7c.png)
![6D5ACC9C-B1C2-4EC4-8EEB-33ED3FF4788A](https://user-images.githubusercontent.com/54649785/152114991-9264df29-2e55-4d08-b10f-48ffcd4e1c8d.png)

Restarting Homebridge initializes the device and also initializes HomeKit automation.  The room settings are also changed to the initial settings.  After this update, symptoms appeared.

**Comment by merdok** [comment] 2022-02-02 08:13
The log looks perfectly fine to me. I do not see any issues here. If you restart homebridge then the plugin needs to initialize alle the devices, this initialization process was also present in the previous release.

**Comment by nicacus** [comment] 2022-02-02 08:23
I have similar issue.
Every time that homebridge restarts, all Homebridge Miot devices lose their location(room) in Homekit.
They are linked to homebridge location.
This looks like that is added new devices.

**Comment by ddong3000** [comment] 2022-02-02 08:23
After a reset, the HomeKit automation also disappears.  It is different from the initialization of the previous release.  Homebridge restart should be suspended as much as possible.  thanks for the reply

**Comment by vanillabearr** [comment] 2022-02-02 08:24
The same behavior. When you restart homebridge server, all device settings in module reset to the original ones and so on every time. I don't think that was intended :

**Comment by merdok** [comment] 2022-02-02 08:32
After the update, the first time you start homebridge that might happen. Afterwards it should not, and the code responsible for that did actually not change since the first release so I am not sure what can cause this.
I also cannot reproduce the issue on my local setup, after restart everything is still the same.

**Comment by chrhee21** [comment] 2022-02-02 13:07
I have same issue. After homebridge restarted, all the name and location given by homekit are disappeared. Because of this, all the automation which is consist of these devices are disappeared or broken.

**Comment by vanillabearr** [comment] 2022-02-02 13:23
> After the update, the first time you start homebridge that might happen. Afterwards it should not, and the code responsible for that did actually not change since the first release so I am not sure what can cause this.
> I also cannot reproduce the issue on my local setup, after restart everything is still the same.

Proof :) https://youtu.be/g40IMRBoHT0

**Comment by merdok** [comment] 2022-02-02 14:20
Could anyone of you post a homebridge debug log with the deepDebugLog parameter set to true? It might be that there is a crash happening during initialization which causes this.

**Comment by vanillabearr** [comment] 2022-02-02 14:47
[homebridge.log.txt](https://github.com/merdok/homebridge-miot/files/7987444/homebridge.log.txt)

**Comment by merdok** [comment] 2022-02-02 16:10
Hmmm, looks good! I do not see any issue here. Not sure what is causing that for you...

**Comment by merdok** [comment] 2022-02-02 23:02
This is a kind of strange issue. I cannot think of any reason why the uuid of an accessory would change since it is generated based on fixed data... but to make sure that this is not the case for you, could somebody of you locally at this line:
https://github.com/merdok/homebridge-miot/blob/663de8134ac3d225032e264ae70d1920c5180641/index.js#L159
put the following code:
`console.log(this.UUID);`
and compare between restarts if that value changes for the same accessories?

**Comment by benchristian88** [comment] 2022-02-03 00:53
happy to do it, but i have no idea where that file is, where would I look? cheers

**Comment by merdok** [comment] 2022-02-03 07:11
Usually under /usr/lib/node_modules/

**Comment by yoonpooh** [comment] 2022-02-03 08:50
`console.log(this.UUID);`
I put that code in and proceeded.

`[2/3/2022, 5:48:48 PM] [miot] [공기청정기] Successfully created a AirPurifier device! It is a Xiaomi Air Purifier Pro 4.

**bfff173f-9e93-4d36-9e29-684963076c3b**

[2/3/2022, 5:48:48 PM] [miot] [공기청정기] Initializing accessory!
[2/3/2022, 5:48:48 PM] [miot] [공기청정기] Accessory successfully initialized!
[2/3/2022, 5:48:48 PM] [miot] [공기청정기] Registering 1 accessories!
[2/3/2022, 5:48:48 PM] [miot] [공기청정기] Everything looks good! Initiating property polling!
[2/3/2022, 5:48:48 PM] [miot] [공기청정기] Device found: zhimi.airp.vb4
[2/3/2022, 5:48:48 PM] [miot] [공기청정기] Setting up miot device!
[2/3/2022, 5:48:48 PM] [miot] [공기청정기] Device setup finished! Miot device ready!
[2/3/2022, 5:48:48 PM] [miot] [공기청정기] [Miot Device] Connected to device: zhimi.airp.vb4
[2/3/2022, 5:48:48 PM] [miot] [공기청정기] Doing initial property fetch.`

**Comment by merdok** [comment] 2022-02-03 09:04
@yoonpooh you need to restart homebridge a couple of times so we can see if that uuid changes between restarts.

**Comment by yoonpooh** [comment] 2022-02-03 09:05
@merdok Restarting homebridge did not change the uuid. However, all locations set in Homekit will be initialized.

**Comment by merdok** [comment] 2022-02-03 09:31
So it is not a problem of changing uuid of the accessory between restarts. Not sure what else could cause this for you guys...
I am unfortunately not able to reproduce your issue locally so this will be a guessing game...

**Comment by yoonpooh** [comment] 2022-02-03 09:33
@merdok This is `zhimi.airp.vb4` which was newly added with this update. Maybe it's related?

**Comment by yoonpooh** [comment] 2022-02-03 10:03
@merdok 
It seems you have found the cause of the issue.
I currently use Homebridge as Synology Docker. The problem seems to occur when using Docker.
I downloaded Homebridge as a **.spk** file and tried again, no problem.

https://github.com/oznu/homebridge-syno-spk

**Comment by ddong3000** [comment] 2022-02-03 10:11
I'm using raspi docker homebridge

**Comment by merdok** [comment] 2022-02-03 10:13
Oh interesting... I wonder why it is happening on docker then. It might be that the cached devices are not properly saved there? And why does it suddenly happen after the update where nothing really related to that has changed...

**Comment by iu3564** [comment] 2022-02-03 10:14
> @merdok It seems you have found the cause of the issue. I currently use Homebridge as Synology Docker. The problem seems to occur when using Docker. I downloaded Homebridge as a **.spk** file and tried again, no problem.
> 
> https://github.com/oznu/homebridge-syno-spk

@merdok, I use same build and have this issue , you need try on this image https://hub.docker.com/r/oznu/homebridge

Alpine Linux (3.12.9)
node v16.13.2
npm v8.1.2

**Comment by yoonpooh** [comment] 2022-02-03 10:36
> Oh interesting... I wonder why it is happening on docker then. It might be that the cached devices are not properly saved there? And why does it suddenly happen after the update where nothing really related to that has changed...

Translate mistakes :(

**Comment by yoonpooh** [comment] 2022-02-03 11:12
@merdok If only "homebridge-miot" is installed, the issue will not occur. In addition, the issue occurred when installing other plugins. Another plugin I installed is "homebridge-mi-humidifier".

**Comment by merdok** [comment] 2022-02-03 12:35
Does it happen only in combination with other plugins? Can the other guys confirm this?

**Comment by nicacus** [comment] 2022-02-03 12:49
> Does it happen only in combination with other plugins? Can the other guys confirm this?

I have also other plugins and the issue exists

**Comment by merdok** [comment] 2022-02-03 13:04
Yeah but does it happen when you remove all other plugins and just keep this?

**Comment by vanillabearr** [comment] 2022-02-03 13:33
> homebridge.log.txt

I'm not sure this will help. In this log, all modules except miot were turned off

**Comment by louliangsheng** [comment] 2022-02-03 14:03
@merdok  After my test, if a Child-Bridge is created for the hb-moit plugin, the reset will not occur. If the Child-Bridge is not created, restarting the homebridge will reset

**Comment by merdok** [comment] 2022-02-03 17:51
Interesting. I wonder if it is related to another plugin... Nevertheless i will need to investigate this...

**Comment by iu3564** [comment] 2022-02-03 18:49
@merdok possible this log will help


[2/3/2022, 8:36:27 PM] [miot] Initializing miot platform...
[2/3/2022, 8:36:27 PM] [miot] Found cached accessory Mi Smart LED Bulb Essential (White and Color)
[2/3/2022, 8:36:27 PM] [miot] Found cached accessory Mi Air Purifier 3/3H
[2/3/2022, 8:36:27 PM] [miot] Found cached accessory Mi Smart Space Heater S
[2/3/2022, 8:36:27 PM] [miot] Found cached accessory Yeelight Screen Light Bar
**[2/3/2022, 8:36:27 PM] [miot] Removing all cached accessories**
[2/3/2022, 8:36:27 PM] [miot] Initializing devices
[2/3/2022, 8:36:27 PM] [miot] [Yeelight Screen Light Bar] Got device configuration, initializing device with name: Yeelight Screen Light Bar
[2/3/2022, 8:36:27 PM] [miot] [Mi Smart Space Heater S] Got device configuration, initializing device with name: Mi Smart Space Heater S
[2/3/2022, 8:36:27 PM] [miot] [Mi Air Purifier 3/3H] Got device configuration, initializing device with name: Mi Air Purifier 3/3H
[2/3/2022, 8:36:27 PM] [miot] [Mi Smart LED Bulb Essential (White and Color)] Got device configuration, initializing device with name: Mi Smart LED Bulb Essential (White and Color)
[2/3/2022, 8:36:27 PM] Publishing bridge accessory (name: Homebridge 3D5B, publishInfo: {

[2/3/2022, 8:36:27 PM] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 3D5B) is running on port 51443.
[2/3/2022, 8:36:27 PM] [miot] [Mi Smart LED Bulb Essential (White and Color)] No cached device info found!
[2/3/2022, 8:36:27 PM] [miot] [Mi Smart LED Bulb Essential (White and Color)] Model known: yeelink.light.color5!
[2/3/2022, 8:36:27 PM] [miot] [Mi Smart LED Bulb Essential (White and Color)] Initializing device!


[homebridge.log.txt](https://github.com/merdok/homebridge-miot/files/7997314/homebridge.log.txt)

**Comment by merdok** [comment] 2022-02-03 18:57
@iu3564 this is fine and intended and it was present in the plugin since the first version :)

**Comment by iu3564** [comment] 2022-02-03 20:13
@merdok I switched miot platform to child bridge and issue is gone

**Comment by benchristian88** [comment] 2022-02-03 20:17
@merdok I also switched miot platform to child bridge and issue is gone.
I am also running homebridge in docker, within portainer in hass.

**Comment by merdok** [comment] 2022-02-03 20:43
That is good to hear that it is now working for you again when you run it as a child bridge, but that should not be the solution. I will be investigating this further and try to provide a proper solution.

**Comment by merdok** [comment] 2022-02-03 21:28
Can please anyone of you try to replace the index.js with this one locally and check if that fixes the issue:
https://gist.github.com/merdok/54db660c9bdfb1ae3e1f941112ab31c4

**Comment by iu3564** [comment] 2022-02-03 23:32
> Can please anyone of you try to replace the index.js with this one locally and check if that fixes the issue:
> https://gist.github.com/merdok/54db660c9bdfb1ae3e1f941112ab31c4
> The file should be at: `/usr/lib/node_modules/homebridge-miot`

 working ok

**Comment by ddong3000** [comment] 2022-02-04 00:49
Great! It has been fixed. THANKS SO MUCH

**Closed** 2022-02-04 00:50 UTC
